services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Application\Http\:
    resource: '%kernel.root_dir%/Application/Http/**/*Controller.php'
    tags: ['controller.service_arguments']