App\Domain\User\Entity\User:
  type: entity
  table: users
  fields:
    username:
      type: string
      length: 255
    login:
      type: string
      unique: true
      length: 60
    password:
      type: string
      length: 255
    roles:
      type: json_array
      length: 20
    isActivated:
      type: boolean
