doctrine_migrations:
  dir_name: '%kernel.project_dir%/src/Migrations'
  # namespace is arbitrary but should be different from App\Migrations
  # as migrations classes should NOT be autoloaded
  namespace: DoctrineMigrations

doctrine:
  dbal:
    types:
      uuid:  Ramsey\Uuid\Doctrine\UuidType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      user:
        type: yml
        prefix: 'App\Domain\User\Entity'
        dir: '%kernel.project_dir%/config/mappings/User'
