doctrine_migrations:
  dir_name: '%kernel.project_dir%/src/Migrations'
  # namespace is arbitrary but should be different from App\Migrations
  # as migrations classes should NOT be autoloaded
  namespace: DoctrineMigrations

doctrine:
  dbal:
    types:
      uuid_binary: Ramsey\Uuid\Doctrine\UuidType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Domain:
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/config/mappings'
        prefix: 'App\Domain'
        alias: Domain
