services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  security.user.api_user_provider:
    class: App\Infrastructure\Security\AuthProvider

  App\Application\Security\LoggedUserProvider:
    autowire: true

  security.firewall.access_denied_handler:
    class: App\Application\Security\AccessDeniedHandler

security:
  encoders:
    App\Application\Security\SecurityAdapter:
      algorithm: bcrypt

  providers:
    api_user_provider:
      id: security.user.api_user_provider

  firewalls:
    token_managment:
      pattern: ^/auth
      stateless: true
      anonymous: true

    under_auth:
      pattern: ^/(?!auth)
      stateless: true
      provider: api_user_provider
      access_denied_handler: security.firewall.access_denied_handler
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
