services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  security.user.api_user_provider:
    class: App\Infrastructure\Security\ApiUserProvider

security:
  providers:
    api_user_provider:
      id: security.user.api_user_provider

  firewalls:
    token_managment:
      pattern: ^/auth
      stateless: true
      anonymous: true

    under_auth:
      pattern: ^/(?!auth)
      stateless: true
      provider: api_user_provider
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
