services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\Doctrine\Listener\MappingConventionListener:
    tags:
      - { name: 'doctrine.event_listener', event: 'loadClassMetadata' }