services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\Common\Transactions\DoctrineTransaction:
    arguments:
      $manager: '@doctrine.orm.entity_manager'

  App\Domain\Common\Transactions\TransactionInterface:
    alias: App\Domain\Common\Transactions\DoctrineTransaction
