imports:
  - { resource: 'jwt_listeners.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  http.listener.json_response:
    class: App\Infrastructure\Http\Listener\JsonResponseListener
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: handle }

  http.listener.validation_exception:
    class: App\Infrastructure\Http\Listener\ValidationExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: handle }

  http.listener.handled_exception:
    class: App\Infrastructure\Http\Listener\HandledExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: handle }
