services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TokenAuthenticator:
    class: App\Application\Security\JwtAuthenticator
    arguments: ['@lexik_jwt_authentication.encoder']
